### ISSUE TITLE
File not found in account

### ISSUE THREAD

**Issue by limaceous-bushwhacker** [architdate/drivedl#3] opened 2020-07-07 15:11 UTC
![Screenshot from 2020-07-07 20-38-26](https://user-images.githubusercontent.com/67668779/86801894-1c40fa00-c092-11ea-9b1d-3079614464d8.png)

Getting this error while using drivedl. It was working a while back. 

I think I accidentally removed it from my Google Dev Console.

EDIT: Added more info.

1. Downloading is also not working, it recognises the ID but the download doesn't actually begin.
2. I can't also search for files within my account.
3. I have readded my account and as well recreated the credentials.json

**Comment by architdate** [comment] 2020-07-07 17:03
Well, there is no `--help` command. The argument after `drivedl` should always be the drive link. It tried to find a link called `--help` that was accessible via one of the 4 accounts you had and didn't find any (obviously). Try `drivedl <link>` and should work! Working as intended.

**Comment by architdate** [comment] 2020-07-07 17:06
Regarding downloads not working, are you sure about that? 

1) What command did you use? 
2) Does the buffer folder create files (should be a `uuid4` based naming schema)
3) an easy way to test is to add the `--noiter` argument. That will tell you before the download starts that it is attempting to download a file

**Comment by architdate** [comment] 2020-07-08 06:01
Closing issue for now since I could not replicate it. Reopen the issue if you are facing these issues again

**Closed as completed by architdate** 2020-07-08 06:01 UTC

**Comment by murdock-commits** [comment] 2020-07-13 12:19
Downloads still not working. Shows Error and `[Rate Limit Count: 20] Partial file saved`

**Comment by architdate** [comment] 2020-07-13 20:32
Unrelated to this specific issue @murdock-commits . Also you are likely attempting to download a file that has been flagged for abuse. The Google Drive API does not allow you to download files flagged for abuse unless you are the file owner.
